#!/bin/bash

#Ejemplo básico de if
#Cuenta el número de argumentos y los clasifica por rangos

numargs=$#

if [ $numargs -eq 0 ]
then
	echo "No hay argumentos"
elif [ $numargs -eq 1 -o $numargs -eq 2 ]
then 
	echo "hay uno o dos argumentos"
elif [ $numargs -le 9 ]
then
	echo "entre 3 y 9 argumentos"
elif [ $numargs -l 19 ]
then	
	echo "entre 10 y 19 argumentos"
else 
	echo "20 0 más argumentos"
fi

