#!/bin/bash

echo "1. Número del ID del proceso, o PID, del shell actual: $$"
echo "2. Nombre del Archivo the actual Script: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values: $*"
echo "Total Number of Parameters : $#"
